function createfigure(data1, data2, data3, data4, data5, data6, data7)
%CREATEFIGURE(DATA1, DATA2, DATA3, DATA4, DATA5, DATA6, DATA7)
%  DATA1:  histogram data
%  DATA2:  histogram data
%  DATA3:  histogram data
%  DATA4:  histogram data
%  DATA5:  histogram data
%  DATA6:  histogram data
%  DATA7:  histogram data

%  Auto-generated by MATLAB on 25-Jan-2018 01:52:45

% Create figure
figure1 = figure('Name',...
    'Swim bout parameters of a WT fish (N=3 fish, n = 906 swim bouts)');

% Create subplot
subplot1 = subplot(3,3,1,'Parent',figure1);
hold(subplot1,'on');

% Create histogram
histogram(data1,'Parent',subplot1,'NumBins',100);

% Create xlabel
xlabel({'time (ms)',''});

% Create title
title('Bout duration (in ms)');

% Create ylabel
ylabel('# of bouts');

box(subplot1,'on');
% Create subplot
subplot2 = subplot(3,3,2,'Parent',figure1);
hold(subplot2,'on');

% Create histogram
histogram(data2,'Parent',subplot2,'NumBins',100);

% Create xlabel
xlabel('angle (deg)');

% Create title
title('Turn angle (in deg)');

% Create ylabel
ylabel('# of bouts');

box(subplot2,'on');
% Create subplot
subplot3 = subplot(3,3,3,'Parent',figure1);
hold(subplot3,'on');

% Create histogram
histogram(data3,'Parent',subplot3,'NumBins',100);

% Create xlabel
xlabel('mean velocity (mm/sec)');

% Create title
title('Mean velocity (mm/sec)');

% Create ylabel
ylabel('# of bouts');

box(subplot3,'on');
% Create subplot
subplot4 = subplot(3,3,4,'Parent',figure1);
hold(subplot4,'on');

% Create histogram
histogram(data4,'Parent',subplot4,'NumBins',100);

% Create xlabel
xlabel('peak velocity (mm/sec)');

% Create title
title('Peak velocity (mm/sec)');

% Create ylabel
ylabel('# of bouts');

box(subplot4,'on');
% Create subplot
subplot5 = subplot(3,3,5,'Parent',figure1);
hold(subplot5,'on');

% Create histogram
histogram(data5,'Parent',subplot5,'NumBins',100);

% Create xlabel
xlabel('distance (mm)');

% Create title
title('Distance per bout (mm)');

% Create ylabel
ylabel('# of bouts');

box(subplot5,'on');
% Create subplot
subplot6 = subplot(3,3,6,'Parent',figure1);
hold(subplot6,'on');

% Create histogram
histogram(data6,'Parent',subplot6,'BinWidth',0.00854);

% Create xlabel
xlabel('angular velocity (deg/sec)');

% Create title
title('Angular velocity (deg/sec)');

% Create ylabel
ylabel('# of bouts');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot6,[0 1]);
box(subplot6,'on');
% Create subplot
subplot7 = subplot(3,3,7,'Parent',figure1);
hold(subplot7,'on');

% Create histogram
histogram(data7,'Parent',subplot7,'BinWidth',1260);

% Create xlabel
xlabel('time (ms)');

% Create title
title('Inter-bout interval (ms)');

% Create ylabel
ylabel('# of bouts');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot7,[0 130000]);
box(subplot7,'on');
